version: "3.4"

services:
  api:
    build: 
      context: .
      dockerfile: ./Locations/src/Locations.API/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - db
  
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    
    environment:
      SA_PASSWORD: "Password."
      ACCEPT_EULA: "Y"